CREATE TABLE `T_ELEC_LICENSE_SB_SUBED` (
`OID`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '主键' ,
`BIZ_ID`  varchar(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '证照主键' ,
`OWNER_ID`  varchar(18) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证照持证人ID' ,
`CONTENT_NAME`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证照目录名称' ,
`INFO_CODE`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证件照面编码' ,
`LSH_CODE`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '电子证照流水号，是电子证照识别的唯一标识' ,
`OWNER_NAME`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '持有者名称' ,
`VERSION`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证照版本' ,
`CONTENT_CODE`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '证照目录编码' ,
`VALID_BEGIN`  datetime NULL DEFAULT NULL COMMENT '证照有效期限开始时间' ,
`VALID_END`  datetime NULL DEFAULT NULL COMMENT '证照有效期限结束时间' ,
`CREATE_TIME`  datetime NULL DEFAULT NULL COMMENT '创建时间' ,
`USER_NAME`  varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '制证人姓名' ,
`USER_CODE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '制证人编码' ,
`IDCARD`  varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '制证人身份标识' ,
`ORG_CODE`  varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '组织机构代码' ,
`ORG_NAME`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '组织机构名称' ,
`OP_TYPE`  varchar(200) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL COMMENT '操作类型' ,
`MODIFY_DATE`  datetime NULL DEFAULT NULL COMMENT '修改时间' ,
`SUB_SYNC_DATE`  datetime NULL DEFAULT NULL COMMENT '同步时间' ,
`SUB_PUSH_FLAG`  varchar(1) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL COMMENT '上报标识 1:已经上报 0: 未上报' ,
`SUB_NUM_TIME`  int(11) NULL DEFAULT NULL COMMENT '推送排序号' ,
PRIMARY KEY (`OID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
ROW_FORMAT=COMPACT;